name: justTeams
version: '${project.version}'
main: eu.kotori.justTeams.JustTeams
api-version: '1.21'
folia-supported: true
load: POSTWORLD
authors: [ kotori ]
description: A powerful teams plugin for multi-server environments with full Folia, Paper, Spigot, and Purpur support.
softdepend: [ Vault, PlaceholderAPI, PvPManager ]
commands:
  team:
    description: Main command for justTeams.
    usage: /<command> [subcommand]
    aliases: [ t ]
  guild:
    description: Alias for the main team command.
    usage: /<command> [subcommand]
    aliases: [ g ]
  clan:
    description: Alias for the main team command.
    usage: /<command> [subcommand]
    aliases: [ c ]
  party:
    description: Alias for the main team command.
    usage: /<command> [subcommand]
    aliases: [ p ]
  teammsg:
    description: Sends a message to your team.
    usage: /<command> <message>
    aliases: [ tm, tmsg ]
  guildmsg:
    description: Sends a message to your team.
    usage: /<command> <message>
    aliases: [ gmsg ]
  clanmsg:
    description: Sends a message to your team.
    usage: /<command> <message>
    aliases: [ cmsg ]
  partymsg:
    description: Sends a message to your team.
    usage: /<command> <message>
    aliases: [ pmsg ]
permissions:
  justteams.*:
    description: Grants all permissions for the plugin.
    children:
      - justteams.admin
      - justteams.user
  justteams.admin:
    description: Grants access to all admin commands and bypasses.
    children:
      - justteams.command.reload
      - justteams.command.admin
      - justteams.bypass.bank.withdraw
      - justteams.bypass.enderchest.use
      - justteams.bypass.home.cooldown
      - justteams.bypass.warp.cooldown
  justteams.user:
    description: Grants access to all standard player commands.
    children:
      - justteams.command.create
      - justteams.command.disband
      - justteams.command.invite
      - justteams.command.accept
      - justteams.command.deny
      - justteams.command.leave
      - justteams.command.kick
      - justteams.command.info
      - justteams.command.chat
      - justteams.command.sethome
      - justteams.command.home
      - justteams.command.settag
      - justteams.command.setdescription
      - justteams.command.transfer
      - justteams.command.promote
      - justteams.command.demote
      - justteams.command.pvp
      - justteams.command.bank
      - justteams.command.enderchest
      - justteams.command.top
      - justteams.command.teammsg
      - justteams.command.join
      - justteams.command.unjoin
      - justteams.command.public
      - justteams.command.requests
      - justteams.command.setwarp
      - justteams.command.delwarp
      - justteams.command.warp
      - justteams.command.warps
  justteams.bypass.bank.withdraw:
    description: Allows bypassing team-specific withdrawal permissions.
    default: op
  justteams.bypass.enderchest.use:
    description: Allows bypassing team-specific ender chest permissions.
    default: op
  justteams.bypass.home.cooldown:
    description: Allows bypassing the /team home teleport cooldown.
    default: op
  justteams.bypass.warp.cooldown:
    description: Allows bypassing the /team warp teleport cooldown.
    default: op
  justteams.command.admin:
    description: Allows access to the /team admin command and GUI.
    default: op
  justteams.command.reload:
    description: Allows reloading the plugin configuration.
    default: op
  justteams.command.create:
    description: Allows creating a team.
    default: true
  justteams.command.disband:
    description: Allows disbanding a team.
    default: true
  justteams.command.invite:
    description: Allows inviting players to a team.
    default: true
  justteams.command.accept:
    description: Allows accepting a team invite.
    default: true
  justteams.command.deny:
    description: Allows denying a team invite.
    default: true
  justteams.command.leave:
    description: Allows leaving a team.
    default: true
  justteams.command.kick:
    description: Allows kicking members from a team.
    default: true
  justteams.command.info:
    description: Allows viewing team information.
    default: true
  justteams.command.chat:
    description: Allows toggling team chat.
    default: true
  justteams.chatspy:
    description: Allows spying on all team chats.
    default: op
  justteams.command.sethome:
    description: Allows setting the team home.
    default: true
  justteams.command.home:
    description: Allows teleporting to the team home.
    default: true
  justteams.command.settag:
    description: Allows changing the team tag.
    default: true
  justteams.command.setdescription:
    description: Allows changing the team description.
    default: true
  justteams.command.transfer:
    description: Allows transferring team ownership.
    default: true
  justteams.command.promote:
    description: Allows promoting a team member.
    default: true
  justteams.command.demote:
    description: Allows demoting a team member.
    default: true
  justteams.command.pvp:
    description: Allows toggling team PvP.
    default: true
  justteams.command.bank:
    description: Allows using the team bank.
    default: true
  justteams.command.enderchest:
    description: Allows using the team ender chest.
    default: true
  justteams.command.top:
    description: Allows viewing the team leaderboards.
    default: true
  justteams.command.teammsg:
    description: Allows sending a message to the team chat.
    default: true
  justteams.command.join:
    description: Allows joining or requesting to join a team.
    default: true
  justteams.command.unjoin:
    description: Allows withdrawing a join request from a team.
    default: true
  justteams.command.public:
    description: Allows toggling a team's public status.
    default: true
  justteams.command.requests:
    description: Allows viewing join requests for a team.
    default: true
  justteams.command.setwarp:
    description: Allows setting a team warp.
    default: true
  justteams.command.delwarp:
    description: Allows deleting a team warp.
    default: true
  justteams.command.warp:
    description: Allows teleporting to a team warp.
    default: true
  justteams.command.warps:
    description: Allows listing team warps or opening the GUI.
    default: true
  justteams.admin.performance:
    description: Allows access to performance monitoring commands.
    default: op